import {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowDown,
  ArrowDownToLine,
  ArrowLeft,
  ArrowRight,
  ArrowRightLeft,
  ArrowUp,
  BadgeCheck,
  BarChart3,
  BookOpen,
  Bot,
  CandlestickChart,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleHelp,
  CirclePlus,
  ClipboardList,
  Clock3,
  Code2,
  Coins,
  Copy,
  Download,
  Droplets,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  Filter,
  FilterX,
  Flag,
  Gavel,
  History,
  Home,
  Inbox,
  Info,
  KeyRound,
  LayoutGrid,
  Lock,
  LockKeyhole,
  Menu,
  Network,
  PanelTopOpen,
  PersonStanding,
  Plus,
  ReceiptText,
  RefreshCw,
  RotateCcw,
  Send,
  Share2,
  Shield,
  ShieldCheck,
  Sparkles,
  Timer,
  Upload,
  User,
  UserPlus,
  Users,
  WalletCards,
  X,
  type LucideIcon,
  type LucideProps,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  account_balance_wallet: WalletCards,
  account_circle_off: User,
  activity: Activity,
  add: Plus,
  add_circle: CirclePlus,
  analytics: BarChart3,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  article: FileText,
  autorenew: RefreshCw,
  badge: BadgeCheck,
  candlestick_chart: CandlestickChart,
  check: Check,
  check_circle: CheckCircle2,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  close: X,
  code: Code2,
  content_copy: Copy,
  download: Download,
  draw: WalletCards,
  enhanced_encryption: LockKeyhole,
  error: AlertCircle,
  expand_more: ChevronDown,
  filter_alt: Filter,
  filter_alt_off: FilterX,
  flag: Flag,
  gavel: Gavel,
  gpp_good: ShieldCheck,
  grid_view: LayoutGrid,
  group: Users,
  help: CircleHelp,
  history: History,
  home: Home,
  hub: Network,
  inbox: Inbox,
  inventory_2: ClipboardList,
  info: Info,
  lock: Lock,
  lock_open: KeyRound,
  menu: Menu,
  menu_book: BookOpen,
  open_in_new: ExternalLink,
  person: PersonStanding,
  person_add: UserPlus,
  pin: EyeOff,
  receipt_long: ReceiptText,
  refresh: RefreshCw,
  report: AlertCircle,
  restart_alt: RotateCcw,
  schedule: Clock3,
  send: Send,
  share: Share2,
  shield: Shield,
  shield_lock: LockKeyhole,
  smart_toy: Bot,
  sparkle: Sparkles,
  swap_horiz: ArrowRightLeft,
  swap_vert: ArrowRightLeft,
  sync: RefreshCw,
  timer: Timer,
  token: Coins,
  upload: Upload,
  verified: BadgeCheck,
  vertical_align_bottom: ArrowDown,
  visibility: Eye,
  visibility_off: EyeOff,
  warning: AlertTriangle,
  water_drop: Droplets,
  arrow_up: ArrowUp,
  arrow_down: ArrowDown,
  arrow_down_to_line: ArrowDownToLine,
  panel: PanelTopOpen,
};

export function Icon({
  name,
  "aria-hidden": ariaHidden = true,
  strokeWidth = 1.75,
  ...props
}: LucideProps & { name: string }) {
  const Component = ICONS[name] ?? Info;
  return (
    <Component
      aria-hidden={ariaHidden}
      focusable="false"
      strokeWidth={strokeWidth}
      {...props}
    />
  );
}
